id: proportion_of_light_trucks_with_short_routes
title: Proportion light trucks with short routes
type: parameter
parameter_type: SOCIOECONOMIC_PARAMETER
unit: percent
tags:
- cohorts
- socioeconomic_parameter
values:
- value: 10
  global: true
  scalingType: CONSTANT
  validFrom: 2019-01-01
  comment: 'Initialized to 10%.

    '
